<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="55942" started-at="2018-02-09T14:19:21Z" finished-at="2018-02-09T14:20:17Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="55942" started-at="2018-02-09T14:19:21Z" finished-at="2018-02-09T14:20:17Z">
      <class name="testCases.CreateUser">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testCases.CreateUser@27ce24aa]" name="setUp" is-config="true" duration-ms="229" started-at="2018-02-09T19:49:21Z" finished-at="2018-02-09T19:49:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="AppOrangeHRMLogin()[pri:0, instance:testCases.CreateUser@27ce24aa]" name="AppOrangeHRMLogin" is-config="true" duration-ms="16508" started-at="2018-02-09T19:49:21Z" finished-at="2018-02-09T19:49:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AppOrangeHRMLogin -->
        <test-method status="PASS" signature="createUser()[pri:0, instance:testCases.CreateUser@27ce24aa]" name="createUser" duration-ms="21208" started-at="2018-02-09T19:49:38Z" finished-at="2018-02-09T19:49:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:testCases.CreateUser@27ce24aa]" name="getResult" is-config="true" duration-ms="83" started-at="2018-02-09T19:49:59Z" finished-at="2018-02-09T19:49:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createUser status=SUCCESS method=CreateUser.createUser()[pri:0, instance:testCases.CreateUser@27ce24aa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="teardown()[pri:0, instance:testCases.CreateUser@27ce24aa]" name="teardown" is-config="true" duration-ms="0" started-at="2018-02-09T19:50:17Z" finished-at="2018-02-09T19:50:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.CreateUser -->
      <class name="testCases.DeletingUser">
        <test-method status="PASS" signature="AppOrangeHRMLogin()[pri:0, instance:testCases.DeletingUser@68999068]" name="AppOrangeHRMLogin" is-config="true" duration-ms="13040" started-at="2018-02-09T19:49:59Z" finished-at="2018-02-09T19:50:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AppOrangeHRMLogin -->
        <test-method status="FAIL" signature="deleteUser()[pri:0, instance:testCases.DeletingUser@68999068]" name="deleteUser" duration-ms="5016" started-at="2018-02-09T19:50:12Z" finished-at="2018-02-09T19:50:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:37)
	at testCases.DeletingUser.deleteUser(DeletingUser.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUser -->
        <test-method status="FAIL" signature="getResult(org.testng.ITestResult)[pri:0, instance:testCases.DeletingUser@68999068]" name="getResult" is-config="true" duration-ms="0" started-at="2018-02-09T19:50:17Z" finished-at="2018-02-09T19:50:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=deleteUser status=FAILURE method=DeletingUser.deleteUser()[pri:0, instance:testCases.DeletingUser@68999068] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utility.GetScreenshot.capture(GetScreenshot.java:16)
	at utility.BaseExtentTest.getResult(BaseExtentTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- testCases.DeletingUser -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
